name: Azure test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
    build-and-deploy:
      runs-on: windows-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - run: |
          $resGroup = "buildgeneric"
          $resLocation = "West Europe"
          $repo = "microsoft/nav-docker"
          $removeResGroupIfExist = $true
          $machines = 2
          $offset = 0
          Write-Host $resGroup
          $resourceGroup = Get-AzureResourceGroup -name $resGroup -ErrorAction Ignore
          if ($resourceGroup) {
            Write-Host "Resource Group Exists"
            exit 1
          }
          $resourceGroup = New-AzureResourceGroup -Name $resGroup -Location $resLocation -Force


